---
- name: Play1
  hosts: test
  tasks:
  - name: create a user
    user: name=user1 state=present
  - name: install a package
    yum: name=httpd state=present
  - name: run a command
    command: uptime
  - name: update system
    command: yum update -y
  - name: reboot system
    reboot:
     msg: "Reboot initiated by Ansible Master"
   

- name: Play2
  hosts: prod
  tasks:
  - name: create a user
    user: name=user1 state=present
  - name: install a package
    yum: name=httpd state=present
  - name: start a service
    service: name=httpd state=started 
  - name: run a command
    command: uptime
  - name: update system
    command: yum update -y
  - name: reboot system
    reboot:
     msg: "Reboot initiated by Ansible Master"