---
 - name: Play1 
   hosts: test
   vars:
    - username:
       - john1
       - sean1
       - paul1

   tasks: 
    - name: Create multiple users
      user: name={{ item }}  state=present
      with_items: "{{username}}"
      tags: user_create
   
 - name: Play2
   hosts: dev
   vars:
    - application:
        - curl
        - docker
   
   tasks:
    - name: Install application
      yum: name={{ application }} state=present
      when: ansible_facts['os_family'] == "CentOS"
      # OR when: ansible_os_family=="Ubuntu" <<< Facts variable
      tags: application_install
  
  
